# title: portfolio
# desc: portofolio of ashwin
# age: 25

# #array
# nav:
# - tech
# - img
# - creative

# #obj
# address:
#   street: vroad
#   city: ch
#   state: TN

#   #env
#   value: ${{env.VALUE}}
#   var: ${{github.vARIABLE-NAME}}


name: Print Node.js Version

on: [push]

jobs:
  print-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Print Node.js version
      run: node -v